### ISSUE TITLE
Large data performance

### ISSUE THREAD

**Issue by justinkx** [friyiajr/expo-sample-pedometer#2]
Thanks @friyiajr  for your in depth tutorial on expo modules API.
I have a use case in which need to migrate a function in JS layer to expo modules.
I do some complex iterations, mappings and sort to a large array of objects currently in JS thread. So any time there is a change in array values, this expensive function re-computes causing heavy lift in JS thread.
Using help of your tutorial, I moved it to expo modules function (passing array as input [it converts them to List, Map in Kotlin ], does all manipulations in native and return the result back). I am getting same result as it was in JS thread 🎉 
But I didn't notice any performance improvement. Some times expo module function takes more time than it's JS equivalent.

**Is it the data conversion back and forth happens through JSI causing it , or should I use new arch for desired perf improvements ?**

**Comment by friyiajr** [comment]
Hi @justinkx, so Turbo Modules are just a wrapper around JSI. If you are using JSI you are using the new architecture. If you are having performance issues I recommend asking the Expo team about it on their public discord: https://discord.com/invite/expo
